name: Unit tests

on:
  pull_request:

env:
  DOWNWARD_BENCHMARKS: "/tmp/downward-benchmarks"
  FSBENCHMARKS: "/tmp/fs-benchmarks"

jobs:
  unit_tests:
    strategy:
      # Keep running all parameter combinations even if one fails
      fail-fast: false

      # We run unit tests on all currently active Python releases, see https://www.python.org/downloads/.
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        experimental: [false]
        include:
          # The Python pre-releases that are available to the GH action are listed here:
          # https://github.com/actions/python-versions/releases
          -  os: ubuntu-latest
             python: '3.11.0-alpha.5'
             experimental: true
#        python-version: [ '2.x', '3.x', 'pypy-2.7', 'pypy-3.7', 'pypy-3.8' ]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Install all dependencies, then get some benchmarks that we'll use to run the tests.
        # Curl below is necessary to download the benchmarks
        run: |
          sudo apt-get install -y --no-install-recommends gringo curl
          python -m pip install --upgrade tox pip setuptools wheel
          gringo --version
          tox --version
          ./scripts/get-benchmarks

      - name: Run tests (Experimental ${{ matrix.experimental }})
        run: |
          tox -v -e pytest
